### PR TITLE
Qld loans

### PR DESCRIPTION
**Pull request by sallybaker**
Added loan periods for those QLD libraries I know to address Issue: #102

### CODE REVIEW

**Comment by hughrun** [comment]
Thanks a bunch for this @sallybaker !

There's a check failing which I need to sort out before I can pull this in (looks to be a problem with my Action, not with your PR).

In the meantime, do you mind updating Winton and Weipa - you list them as '28' instead of '4' (weeks).

**Comment by sallybaker** [comment]
Whoops! Can do. The system works on days, not weeks ;)

**Comment by hughrun** [comment]
Hi @sallybaker  can you please cancel this PR, pull the latest from `master`, and then open a new PR? I want to test whether the 'Action' that updates the topo.json file will work on a fresh PR on the same branch you used.

**Comment by sallybaker** [comment]
Cancelling PR

**Pull request closed without merging**
